commit policy
RedHat-SP-Security/tests pull request #28
Opened 2021-04-08 13:58 UTC by sopos

a description of the commit and review process

2021-04-08 14:05 UTC, sergio-correia commented on README.md
> +Small, trivialy changes may be committed directly the master branch.
typo: trivial

2021-04-08 14:07 UTC, sergio-correia commented on README.md
> +The marge it self should be done based on the accepted reviews. It is recommended to let the original requestor to merge the PR as they may want to do some refinements, e.g. quash some commits which
typos: The merge itself / e.g. squash

2021-04-08 14:14 UTC, sopos commented on README.md
> +Every important change to tests should undergo a review withing a pull request.
```suggestion
Every important change to tests should undergo a review within a pull request.
```

2021-04-08 14:19 UTC, sopos commented on README.md
> +Small, trivialy changes may be committed directly the master branch.
```suggestion
Small, trivial changes may be committed directly the master branch.
```

2021-04-08 14:19 UTC, sopos commented on README.md
> +As a typical trivial change one may considere a metadata update (updated tags, adjust, ..)
```suggestion
As a typical trivial change one may consider a metadata update (updated tags, adjust, ..)
```

2021-04-08 14:19 UTC, sopos commented on README.md
> +All changes to the test logic (changes of expected output, expected exit codes) need to be reviewd.
```suggestion
All changes to the test logic (changes of expected output, expected exit codes) need to be reviewed.
```

2021-04-08 14:19 UTC, sopos commented on README.md
> +The review can be done by any member of the team. However, it is recommended to ask the devel counterpart as they could judge the test expectations according to the actualy code change. Asking anothe
```suggestion
The review can be done by any member of the team. However, it is recommended to ask the devel counterpart as they could judge the test expectations according to the actual code change. Asking another QE person, on the other hand, will ensure to keep the test coding style as consistent as possible.
```

2021-04-08 14:19 UTC, sopos commented on README.md
> +The marge it self should be done based on the accepted reviews. It is recommended to let the original requestor to merge the PR as they may want to do some refinements, e.g. quash some commits which
```suggestion
The merge it self should be done based on the accepted reviews. It is recommended to let the original requestor to merge the PR as they may want to do some refinements, e.g. squash some commits which were added during the review process.
```

2021-04-12 13:30 UTC, radosroka approved these changes

2021-04-12 13:34 UTC, ZelenyMartin requested changes

2021-04-12 13:34 UTC, ZelenyMartin commented on README.md
> +Small, trivial changes may be committed directly the master branch.
directly **to** the master branch

2021-04-12 13:50 UTC, sopos commented on README.md
> +Small, trivial changes may be committed directly the master branch.
```suggestion
Small, trivial changes may be committed directly to the master branch.
```

2021-04-12 15:20 UTC, ZelenyMartin approved these changes

2021-04-14 05:31 UTC, Cropi approved these changes

2021-04-16 11:22 UTC, merged